### ISSUE TITLE
test mode cannot print block shape

### ISSUE THREAD

**Issue by YesDargo** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#27]
This is the print info after running '--option=test'. 
Did anyone encounter the same problem?

```
-----------build encoder: deeplab pre-trained-----------
after start block: (1, ?, ?, 64)
after block1: (1, ?, ?, 256)
after block2: (1, ?, ?, 512)
after block3: (1, ?, ?, 1024)
after block4: (1, ?, ?, 2048)
-----------build decoder-----------
after aspp block: (1, ?, ?, 2)
```

**Comment by John1231983** [comment]
`?` mean arbitrary shape because it applies fully convolution. Shape `?` means the width and height can be any size. In training, you have cropped to 312, so it can be showed in training but testing/prediction does not require it

**Comment by YesDargo** [comment]
I train on other dataset which aims to separate foreground and background(two classes), but images of [ labels, predict] in tensorboard are all black.

Do you have any idea to modify the RGB labels to binary image?

**Comment by zhengyang-wang** [comment]
What do you mean by RGB labels?

Suppose you have n classes. Your labels are always gray images, and only have values of integers in [0,n-1]. Like PASCAL, the labels are gray images with only integer values in [0,20].

Some cases (like PASCAL here) have some value 255 pixels in the labels. This is simply because we don't care about those pixels and they will be ignored in training and testing.
